# SPDX-FileCopyrightText: 2023-2026 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# Pre-checks

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: "The `sqlite_database_path` variable needs to be provided to this playbook, via --extra-vars"
  when: "sqlite_database_path is not defined or sqlite_database_path.startswith('<')"

- name: Check if the provided SQLite database file exists
  ansible.builtin.stat:
    path: "{{ sqlite_database_path }}"
  register: sqlite_database_path_stat_result

- name: Fail if provided SQLite database file doesn't exist
  ansible.builtin.fail:
    msg: "File cannot be found on the server at {{ sqlite_database_path }}"
  when: "not sqlite_database_path_stat_result.stat.exists"

# We either expect `postgis_db_connection_string` specifying a full PostGIS database connection string,
# or `postgis_connection_string_variable_name`, specifying a name of a variable, which contains a valid connection string.

- when: "postgis_connection_string_variable_name is defined"
  block:
    - name: Fail if postgis_connection_string_variable_name points to an undefined variable
      ansible.builtin.fail:
        msg: "postgis_connection_string_variable_name is defined, but there is no variable with the name `{{ postgis_connection_string_variable_name }}`"
      when: "lookup('ansible.builtin.varnames', ('^postgis_connection_string_variable_name$'), wantlist=True) | length == 0"

    - name: Get PostGIS connection string from variable
      ansible.builtin.set_fact:
        postgis_db_connection_string: "{{ lookup('vars', postgis_connection_string_variable_name) }}"

- name: Fail if playbook called incorrectly
  ansible.builtin.fail:
    msg: >-
      Either a `postgis_db_connection_string` variable or a `postgis_connection_string_variable_name` needs to be provided to this playbook, via `--extra-vars`.
      Example: `--extra-vars="postgis_db_connection_string=postgresql://username:password@localhost:<port>/database_name"` or `--extra-vars="postgis_connection_string_variable_name=some_variable_connString"`
  when: "postgis_db_connection_string is not defined or not postgis_db_connection_string.startswith('postgresql://')"

# Defaults

- name: Set postgis_start_wait_time, if not provided
  ansible.builtin.set_fact:
    postgis_start_wait_time: 15
  when: "postgis_start_wait_time | default('') == ''"

# Actual import work

- name: Ensure PostGIS service is started
  ansible.builtin.service:
    name: "{{ postgis_identifier }}"
    state: started
    daemon_reload: true
  register: postgis_ensure_started_result

- name: Wait a bit, so that PostGIS can start
  ansible.builtin.wait_for:
    timeout: "{{ postgis_start_wait_time }}"
  delegate_to: 127.0.0.1
  become: false
  when: "postgis_ensure_started_result.changed | bool"

- name: Import SQLite database from {{ sqlite_database_path }} into PostGIS # noqa name[template]
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} run
      --rm
      --user={{ postgis_container_uid }}:{{ postgis_container_gid }}
      --cap-drop=ALL
      --network={{ postgis_container_network }}
      --mount type=bind,src={{ sqlite_database_path }},dst=/in.db,ro
      --entrypoint={{ postgis_container_shell_path }}
      {{ postgis_pgloader_container_image }}
      -c
      'pgloader /in.db {{ postgis_db_connection_string }}'
  register: postgis_import_generic_sqlite_db_import_result
  changed_when: postgis_import_generic_sqlite_db_import_result.rc == 0

- name: Archive SQLite database ({{ sqlite_database_path }} -> {{ sqlite_database_path }}.backup) # noqa name[template]
  ansible.builtin.command:
    cmd: "mv {{ sqlite_database_path }} {{ sqlite_database_path }}.backup"
  register: postgis_import_generic_sqlite_db_move_result
  changed_when: postgis_import_generic_sqlite_db_move_result.rc == 0

- name: Inject result
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "NOTE: Your SQLite database file has been imported into PostGIS. The original file has been moved from `" + sqlite_database_path + "` to `" + sqlite_database_path + ".backup`. When you've confirmed that the import went well and everything works, you should be able to safely delete this file."
        ]
      }}

- name: Ensure PostGIS is stopped (if it previously was)
  when: "postgis_ensure_started_result.changed | bool"
  ansible.builtin.service:
    name: "{{ postgis_identifier }}"
    state: stopped
