# SPDX-FileCopyrightText: 2023-2026 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- ansible.builtin.import_tasks: "{{ role_path }}/tasks/migrate_postgis_data_directory.yml"

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/detect_existing_postgis_version.yml"

- when: postgis_detected_existing | bool
  block:
    - name: Abort if on an unsupported PostGIS version
      ansible.builtin.fail:
        msg: "You're on PostGIS {{ postgis_detected_version }}, which is no longer supported. To upgrade, see docs/maintenance-postgis.md"
      when: "postgis_detected_version_number == 9"

    - name: Inject warning if detected PostGIS version number not eligible
      when: "postgis_detected_version_number not in postgis_eligible_versions"
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "WARNING: We detected that PostGIS version (" + postgis_detected_version_number | string + ") is already installed, but it's not normally eligible for installation for your setup. You or some other role is currently restricting `postgis_allowed_versions` to " + postgis_allowed_versions | to_json + " for compatibility reasons. Perhaps this other role does not support other PostGIS versions. You can suppress this warning by force-settting `postgis_allowed_versions` to something like [" + postgis_detected_version_number | to_json + "], though it would be better to figure out where the restriction comes from and to potentially downgrade PostGIS to the maximum allowed version (" + postgis_eligible_version_max | string + ") imposed by the current restrictions.",
            ]
          }}

    - name: Inject warning if on maximum eligible PostGIS version, but held back from the maximum known version
      when: "postgis_detected_version_number == postgis_eligible_version_max and postgis_eligible_version_max < postgis_known_version_max"
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "NOTE: We detected that PostGIS version (" + postgis_detected_version_number | string + ") is already installed. While a newer version (" + postgis_known_version_max | string + ") is normally available, it's not eligible for installation for your setup. You or some other role is currently restricting `postgis_allowed_versions` (likely via `postgis_allowed_versions_auto` or `postgis_allowed_versions_custom`) to " + postgis_allowed_versions | to_json + " for compatibility reasons. Perhaps this other role does not support the newer PostGIS version.",
            ]
          }}

    - name: Inject warning if on an old version of PostGIS
      ansible.builtin.set_fact:
        devture_playbook_runtime_messages_list: |
          {{
            devture_playbook_runtime_messages_list | default([])
            +
            [
              "NOTE: Your setup is on an old PostGIS version (" + postgis_detected_version_number | string + ") and can be upgraded to version " + postgis_available_upgrade_versions | max | string + ". You can upgrade using --tags=upgrade-postgis"
            ]
          }}
      when: "postgis_detected_existing and postgis_available_upgrade_versions | length > 0"

    # If we have found an existing version (installed from before), we use its corresponding container image.
    # If not, we let `postgis_container_image_to_use` default to the latest eligible version.
    #
    # Upgrading is supposed to be performed separately and explicitly (see `upgrade_postgis.yml`).
    - ansible.builtin.set_fact:
        postgis_container_image_to_use: "{{ postgis_detected_version_corresponding_container_image }}"

# Even if we don't run the internal server, we still need this for running the CLI
- name: Ensure PostGIS container image is pulled
  community.docker.docker_image_pull:
    name: "{{ postgis_container_image_to_use }}"
    pull: always
  register: postgis_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: postgis_container_image_pull_result is not failed

- name: Ensure PostGIS paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ postgis_uid }}"
    group: "{{ postgis_gid }}"
  with_items:
    - "{{ postgis_base_path }}"
    - "{{ postgis_data_path }}"
    - "{{ postgis_bin_path }}"

- name: Ensure PostGIS run path exists
  ansible.builtin.file:
    path: "{{ postgis_run_path }}"
    state: directory
    mode: "0755"
    owner: "{{ postgis_uid }}"
    group: "{{ postgis_gid }}"
  when: postgis_container_unix_socket_enabled
# Separate task to allow different permissions for unix socket access.

- name: Ensure PostGIS environment variables file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ postgis_base_path }}/{{ item }}"
    owner: "{{ postgis_uid }}"
    group: "{{ postgis_gid }}"
    mode: "0640"
  with_items:
    - "env-postgis-psql"
    - "env-postgis-server"
  register: postgis_config_file_result

- name: Ensure PostGIS scripts created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/bin/{{ item }}.j2"
    dest: "{{ postgis_bin_path }}/{{ item }}"
    mode: "0755"
  with_items:
    - cli
    - cli-non-interactive
    - dump-all
  register: postgis_scripts_result

- name: Ensure PostGIS container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ postgis_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure PostGIS systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/postgis.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ postgis_identifier }}.service"
    mode: "0644"
  register: postgis_systemd_service_result

- name: Determine whether PostGIS needs a restart
  ansible.builtin.set_fact:
    postgis_restart_necessary: >-
      {{
        postgis_config_file_result.changed | default(false)
        or postgis_scripts_result.changed | default(false)
        or postgis_systemd_service_result.changed | default(false)
        or postgis_container_image_pull_result.changed | default(false)
      }}

- name: Ensure managed PostGIS databases prepared
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/util/prepare_managed_databases.yml"
    apply:
      tags:
        - always
  when: "postgis_managed_databases|length > 0"

- name: Check existence of PostGIS backup data path
  ansible.builtin.stat:
    path: "{{ postgis_data_path }}-auto-upgrade-backup"
  register: postgis_data_backup_path_stat

- name: Inject warning if backup data remains
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "NOTE: You have some PostGIS backup data in `" + postgis_data_path + "-auto-upgrade-backup`, which was created during the last major PostGIS update you ran. If your setup works well after this upgrade, feel free to delete this whole directory."
        ]
      }}
  when: "postgis_data_backup_path_stat.stat.exists"
