---

- name: Check existence of Postgis systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ postgis_identifier }}.service"
  register: postgis_service_stat

- when: postgis_service_stat.stat.exists | bool
  block:
    - name: Ensure Postgis is stopped
      ansible.builtin.service:
        name: "{{ postgis_identifier }}"
        state: stopped
        daemon_reload: true

    - name: Ensure Postgis systemd service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ postgis_identifier }}.service"
        state: absent

    - name: Remove Postgis scripts
      ansible.builtin.file:
        path: "{{ postgis_bin_path }}"
        state: absent

- name: Check existence of Postgis local data path
  ansible.builtin.stat:
    path: "{{ postgis_data_path }}"
  register: postgis_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject warning if Postgis local data remains
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "NOTE: You are not using a local PostgreSQL database, but some old data remains from before in `{{ postgis_data_path }}`. Feel free to delete it."
        ]
      }}
  when: postgis_data_path_stat.stat.exists | bool
