# SPDX-FileCopyrightText: 2023-2026 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Set default postgis_dump_dir, if not provided
  ansible.builtin.set_fact:
    postgis_dump_dir: "/tmp"
  when: "postgis_dump_dir | default('') == ''"

- name: Set postgis_dump_name, if not provided
  ansible.builtin.set_fact:
    postgis_dump_name: "{{ postgis_identifier }}-dump.sql.zst"
  when: "postgis_dump_name | default('') == ''"

- name: Set postgis_auto_upgrade_backup_data_path, if not provided
  ansible.builtin.set_fact:
    postgis_auto_upgrade_backup_data_path: "{{ postgis_data_path }}-auto-upgrade-backup"
  when: "postgis_auto_upgrade_backup_data_path | default('') == ''"

- name: Set postgis_start_wait_time, if not provided
  ansible.builtin.set_fact:
    postgis_start_wait_time: 15
  when: "postgis_start_wait_time | default('') == ''"

- name: Set postgis_force_upgrade, if not provided
  ansible.builtin.set_fact:
    postgis_force_upgrade: false
  when: "postgis_force_upgrade | default('') == ''"

- name: Check PostGIS auto-upgrade backup data directory
  ansible.builtin.stat:
    path: "{{ postgis_auto_upgrade_backup_data_path }}"
  register: result_auto_upgrade_path

- name: Abort, if existing PostGIS auto-upgrade data path detected
  ansible.builtin.fail:
    msg: |-
      Detected that a left-over {{ postgis_auto_upgrade_backup_data_path }} exists.
      You should rename it to {{ postgis_data_path }} if the previous upgrade went wrong, or delete it if it went well.
  when: "result_auto_upgrade_path.stat.exists"

- name: Detect existing PostGIS version
  ansible.builtin.import_tasks: tasks/detect_existing_postgis_version.yml

- name: Abort, if no existing PostGIS version detected
  ansible.builtin.fail:
    msg: "Could not find existing PostGIS installation"
  when: "not postgis_detected_existing | bool"

- name: Abort, if already at latest PostGIS version
  ansible.builtin.fail:
    msg: "You are already running the latest PostGIS version supported ({{ postgis_container_image_latest }}). You can force an 'upgrade' anyway by passing `-e postgis_force_upgrade=true` to the playbook."
  when: "postgis_detected_version_number == postgis_eligible_version_max and not postgis_force_upgrade"

- ansible.builtin.debug:
    msg: "Upgrading the PostGIS database from version {{ postgis_detected_version_number }} to the maximum eligible version ({{ postgis_eligible_version_max }})"

- name: Ensure services are stopped
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    daemon_reload: true
  with_items: "{{ postgis_systemd_services_to_stop_for_maintenance_list }}"

- name: Ensure PostGIS service is started
  ansible.builtin.service:
    name: "{{ postgis_identifier }}"
    state: started
    daemon_reload: true
  register: postgis_ensure_started_result

- name: Wait a bit, so that PostGIS can start
  when: postgis_ensure_started_result.changed | bool
  ansible.builtin.wait_for:
    timeout: "{{ postgis_start_wait_time }}"
  delegate_to: 127.0.0.1
  become: false

# We dump all databases, roles, etc.
#
# Because we'll be importing into a new container which initializes the default
# role (`postgis_connection_username`) and database (`postgis_db_name`) by itself on startup,
# we need to remove these from the dump, or we'll get errors saying these already exist.
- name: Perform PostGIS database dump
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} run --rm --name {{ postgis_identifier }}-dump
      --log-driver=none
      --user={{ postgis_container_uid }}:{{ postgis_container_gid }}
      --network={{ postgis_container_network }}
      --env-file={{ postgis_base_path }}/env-postgis-psql
      --entrypoint={{ postgis_container_shell_path }}
      --mount type=bind,src={{ postgis_dump_dir }},dst=/out
      {{ postgis_detected_version_corresponding_container_image }}
      -c "pg_dumpall -h {{ postgis_identifier }}
      {{ '| gzip -c ' if postgis_dump_name.endswith('.gz') else '' }}
      {{ '| zstd --stdout ' if postgis_dump_name.endswith('.zst') else '' }}
      > /out/{{ postgis_dump_name }}"
  register: postgis_upgrade_postgis_dump_command_result
  changed_when: postgis_upgrade_postgis_dump_command_result.rc == 0
  tags:
    - skip_ansible_lint

- name: Ensure PostGIS is stopped
  ansible.builtin.service:
    name: "{{ postgis_identifier }}"
    state: stopped

- name: Rename existing PostGIS data directory
  ansible.builtin.command:
    cmd: "mv {{ postgis_data_path }} {{ postgis_auto_upgrade_backup_data_path }}"
  register: postgis_upgrade_postgis_move_command_result
  changed_when: postgis_upgrade_postgis_move_command_result.rc == 0

- ansible.builtin.debug:
    msg: "NOTE: Your PostGIS data directory has been moved from `{{ postgis_data_path }}` to `{{ postgis_auto_upgrade_backup_data_path }}`. In the event of failure, you can stop services, move it back and run the playbook with --tags=setup-postgis to restore operation on the old PostGIS version ({{ postgis_detected_version_number }})."

- name: Install PostGIS
  ansible.builtin.import_tasks: tasks/install.yml

- name: Ensure PostGIS autoruns and is restarted
  ansible.builtin.service:
    name: "{{ postgis_identifier }}"
    enabled: true
    state: restarted
    daemon_reload: true

- name: Wait a bit, so that PostGIS can start
  ansible.builtin.wait_for:
    timeout: "{{ postgis_start_wait_time }}"
  delegate_to: 127.0.0.1
  become: false

# Starting the database container had automatically created the default
# role (`postgis_connection_username`) and database (`postgis_db_name`).
# The dump most likely contains those same entries and would try to re-create them, leading to errors.
# We need to skip over those lines.
- name: Generate PostGIS database import command
  ansible.builtin.set_fact:
    postgis_import_command: >-
      {{ devture_systemd_docker_base_host_command_docker }} run --rm --name {{ postgis_identifier }}-import
      --log-driver=none
      --user={{ postgis_container_uid }}:{{ postgis_container_gid }}
      --cap-drop=ALL
      --network={{ postgis_container_network }}
      --env-file={{ postgis_base_path }}/env-postgis-psql
      --entrypoint={{ postgis_container_shell_path }}
      --mount type=bind,src={{ postgis_dump_dir }},dst=/in,ro
      {{ postgis_container_image_latest }}
      -c "cat /in/{{ postgis_dump_name }} |
      {{ 'gunzip |' if postgis_dump_name.endswith('.gz') else '' }}
      {{ 'unzstd |' if postgis_dump_name.endswith('.zst') else '' }}
      {% if postgis_import_roles_to_ignore | length > 0 %}
      grep -vE '{{ postgis_import_roles_ignore_regex }}' |
      {% endif %}
      {% if postgis_import_databases_to_ignore | length > 0 %}
      grep -vE '{{ postgis_import_databases_ignore_regex }}' |
      {% endif %}
      {% if postgis_import_schemas_to_ignore | length > 0 %}
      grep -vE '{{ postgis_import_schemas_ignore_regex }}' |
      {% endif %}
      psql -h {{ postgis_identifier }}"
  tags:
    - skip_ansible_lint

# This is a hack.
# See: https://ansibledaily.com/print-to-standard-output-without-escaping/
#
# We want to run `debug: msg=".."`, but that dumps it as JSON and escapes double quotes within it,
# which ruins the command (`postgis_import_command`)
- name: Note about PostGIS importing
  ansible.builtin.set_fact:
    dummy: true
  with_items:
    - >-
      Importing PostGIS database using the following command: `{{ postgis_import_command }}`.
      If this crashes, you can stop PostGIS (`systemctl stop {{ postgis_identifier }}`),
      delete the new database data (`rm -rf {{ postgis_data_path }}`)
      and restore the automatically-made backup (`mv {{ postgis_auto_upgrade_backup_data_path }} {{ postgis_data_path }}`).

- name: Perform PostGIS database import
  ansible.builtin.command:
    cmd: "{{ postgis_import_command }}"
  register: postgis_upgrade_postgis_import_command_result
  changed_when: postgis_upgrade_postgis_import_command_result.rc == 0

- name: Delete PostGIS database dump file
  ansible.builtin.file:
    path: "{{ postgis_dump_dir }}/{{ postgis_dump_name }}"
    state: absent

- name: Ensure PostGIS is stopped (if it previously was)
  when: "postgis_ensure_started_result.changed | bool"
  ansible.builtin.service:
    name: "{{ postgis_identifier }}"
    state: stopped

- name: Ensure services are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    daemon_reload: true
  with_items: "{{ postgis_systemd_services_to_stop_for_maintenance_list }}"

- ansible.builtin.debug:
    msg: "NOTE: Your old PostGIS data directory is preserved at `{{ postgis_auto_upgrade_backup_data_path }}`. You might want to get rid of it once you've confirmed that all is well."
