---

- name: Fail if required Postgres settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - postgis_identifier
    - postgis_uid
    - postgis_gid
    - postgis_container_network
    - postgis_connection_hostname
    - postgis_connection_port
    - postgis_connection_username
    - postgis_connection_password
    - postgis_db_name
    - postgis_architecture

- name: Fail if Postgres password length exceeded
  ansible.builtin.fail:
    msg: "The maximum `postgis_connection_password` length is 99 characters"
  when: "postgis_connection_password | length > 99"
