---

# It'd be better if this is belonged to `validate_config.yml`, but it would have to be some loop-within-a-loop there,
# and that's ugly. We also don't expect this to catch errors often. It's more of a defensive last-minute check.
- name: Fail if managed database data appears invalid
  ansible.builtin.fail:
    msg: "Managed database definition ({{ managed_db }} lacks a required key: {{ item }}"
  when: "item not in managed_db"
  with_items: "{{ ['name', 'username', 'password'] }}"

# The SQL statements that we'll run against Postgres are stored in a file that others can't read.
# This file will be mounted into the container and fed to Postgres.
# This way, we avoid passing sensitive data around in CLI commands that other users on the system can see.
- name: Create managed database initialization SQL file for {{ managed_db.name }}
  ansible.builtin.template:
    src: "{{ role_path }}/templates/sql/init-managed-db-user-and-role.sql.j2"
    dest: "/tmp/{{ postgis_identifier }}-init-managed-db-user-and-role.sql"
    mode: 0600
    owner: "{{ postgis_uid }}"
    group: "{{ postgis_gid }}"

- name: Execute Postgres managed database initialization SQL file for {{ managed_db.name }}
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} run
      --rm
      --user={{ postgis_uid }}:{{ postgis_gid }}
      --cap-drop=ALL
      --env-file={{ postgis_base_path }}/env-postgis-psql
      --network={{ postgis_container_network }}
      --mount type=bind,src=/tmp/{{ postgis_identifier }}-init-managed-db-user-and-role.sql,dst=/{{ postgis_identifier }}-init-managed-db-user-and-role.sql,ro
      --entrypoint=/bin/sh
      {{ postgis_container_image_to_use }}
      -c
      'psql -h {{ postgis_connection_hostname }} --file=/{{ postgis_identifier }}-init-managed-db-user-and-role.sql'
  changed_when: true

- name: Delete managed database initialization SQL file for {{ managed_db.name }}
  ansible.builtin.file:
    path: /tmp/{{ postgis_identifier }}-init-managed-db-user-and-role.sql
    state: absent
