---

- name: Generate Postgres database vacuum command
  ansible.builtin.set_fact:
    postgis_vacuum_command: >-
      {{ devture_systemd_docker_base_host_command_docker }} run
      --rm
      --name={{ postgis_identifier }}-vacuum
      --user={{ postgis_uid }}:{{ postgis_gid }}
      --cap-drop=ALL
      --network={{ postgis_container_network }}
      --env-file={{ postgis_base_path }}/env-postgres-psql
      {{ postgis_detected_version_corresponding_docker_image }}
      psql -v ON_ERROR_STOP=1 -h {{ postgis_identifier }} {{ postgis_database_to_vacuum }} -c 'VACUUM FULL VERBOSE'

- name: Note about Postgres vacuum alternative
  ansible.builtin.debug:
    msg: >-
      Running vacuum against the `{{ postgis_database_to_vacuum }}` database with the following Postgres command:
      `{{ postgis_vacuum_command }}`.
      If this crashes, you can stop all processes which may use the database (`systemctl stop example.service another.service`),
      start Postgres only (`systemctl start {{ postgis_identifier }}`)
      and manually run the above command directly on the server.

- name: Run Postgres vacuum command
  ansible.builtin.command:
    cmd: "{{ postgis_vacuum_command }}"
  async: "{{ postgres_vacuum_wait_time }}"
  poll: 10
  register: postgis_vacuum_result
  failed_when: not postgis_vacuum_result.finished or postgis_vacuum_result.rc != 0
  changed_when: postgis_vacuum_result.finished and postgis_vacuum_result.rc == 0

# Intentionally show the results
- ansible.builtin.debug:
    var: "postgis_vacuum_result"
